### ISSUE TITLE
There is no ability to pass a db password without manually providing it in cmd args

### ISSUE THREAD

**Issue by yunmikun2** [yunmikun2/dbviz#1]
That leaves the password in a shell history. It would be nice to have two possible options: provide the password via env vars and ask the user for a password if it doesn't match or if a special cmd argument is provided.

**Comment by salfum** [comment]
Or maybe store the password in a file like in `.pgpass`?

**Comment by yunmikun2** [comment]
An ability to pass a password via PGPASSWORD was added here https://github.com/yunmikun2/dbviz/commit/a0372cfd351561dd5f064fab4d24b616dac77dab
